### ISSUE TITLE
Grace period for valid?

### ISSUE THREAD

**Issue by Hermanverschooten** [dashbitco/nimble_totp#14]
Is it possible to add a `grace_period` to the `validate?` function.
That would allow to specify how many `:period` before the current are still valid.
This avoids having the code roll-over as you are entering it.

`totpex` supports this, but I would love to use this library.

**Comment by josevalim** [comment]
Hrm, I am wondering if that is considered safe? It seems the roll over will always happen, instead of happening within 30 seconds, now it will happen within 30 seconds + grace period. :) No?

**Comment by Hermanverschooten** [comment]
The idea is that a code will be valid for n times the initial time, without changing the initial time.
It is a bit less secure. But as an option, I know many sites employ it.
eg, if you specify a `:grace_period` of 1, and the initial time is 30, the code will be `valid?` for 60 seconds, but will still roll over every 30 seconds.

**Comment by josevalim** [comment]
I see. I believe you can achieve this today by doing something like this:

    time = System.os_time(:second)
    NimbleTOTP.valid?(secret, otp, time: time) or NimbleTOTP.valid?(secret, otp, time: time - 30)

Is this good enough? I would be very worried about supporting more than double of the original time.

**Comment by josevalim** [comment]
Sounds good. Could you please send a PR to improve the docs then? :)

**Comment by Hermanverschooten** [comment]
Done
