### ISSUE TITLE
Spec for valid? seems wrong

### ISSUE THREAD

**Issue by kuon** [dashbitco/nimble_totp#19]
This spec for `valid?/3` seems to be missing one argument 

` @spec valid?(binary(), [option() | validate_option()]) :: boolean()`

https://github.com/dashbitco/nimble_totp/blob/e90f09e57853b91bf5efb7c5187e95b1dc83f28b/lib/nimble_totp.ex#L233

**Comment by josevalim** [comment]
Please submit a PR!

**Comment by kuon** [comment]
Actually I didn't see 3f28fe1d96e3a199b0133514dceb8097b8e62e8c which fixes it.

Can we have a new release?
