### ISSUE TITLE
My tests fail randomly

### ISSUE THREAD

**Issue by ferigis** [dashbitco/nimble_totp#21]
OS: Mac 12.3.1
Erlang: OTP 24
Elixir: 1.13.4

Hi! first of all thanks for this library, very clean and little!

I am getting a weird behaviour on my tests, not always but is random. The problem is validating an otp with the secret.

If I execute a test like this it fails frequently:

```elixir
  test "probably will fail" do
      for _ <- 0..10000 do
        secret = Base.encode64(NimbleTOTP.secret())
        otp = NimbleTOTP.verification_code(secret)
        Process.sleep 5
        assert NimbleTOTP.valid?(secret, otp)
      end
    end
```

thanks!

**Comment by josevalim** [comment]
Yes, that's expected because time passes. :) Use the `:time` option to make sure the time for verification and valid? match. A PR that improves the docs is welcome.

**Comment by ferigis** [comment]
hi Jose, thanks for the reply. I am not sure I understood :S if I generate an otp now it should be valid during 30 seconds, is that right? if we have to match the otp's generation time with the valid? one how is going to work when using external topt apps like google authenticator? probably is a dumb question but... :)

**Comment by josevalim** [comment]
No, it is not valid from generation. The 30 seconds intervals are fixed. That's why when you open your Google Authenticator some times are expiring... the same happens in tests.

**Comment by ferigis** [comment]
it was a dumb question then :) thanks for the clarification!
