### ISSUE TITLE
Default shared secret byte length

### ISSUE THREAD

**Issue by jared-mackey** [dashbitco/nimble_totp#5]
Hi, thanks for the great library! 

I'm reviewing the source code for this and it looks like it's using a default of 10 bytes (80bits) for the shared secret. The [RFC for HOTP](https://tools.ietf.org/html/rfc4226) says a minimum of 128bits but recommends to use 160bits. Should this library propagate the recommendation from the RFC and set a default of 20 bytes? 

Curious on your thoughts. Thanks.

**Comment by josevalim** [comment]
Yes, please do send a PR! :)

**Comment by jared-mackey** [comment]
Happy to! I'll get that sent over soon.
